config/routes.rb
Rails.application.routes.draw do
  root 'blogs#home'
  get 'blogs/notification'
  post 'blogs/notification'
  post 'blogs/myblog'
  get 'change_val/:id', to: 'blogs#change_val', as: 'change_val'
  devise_for :users
  resources :blogs do
  resources :comments
  end
  resources :blogs do
  resources :likes
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 before_action :authenticate_user!,except: []
def new
  @blog = Blog.new
end
 
 def index
 	@blog=Blog.all
 end
 def destroy
 	  @blog = Blog.find(params[:id])
 	  @blog.destroy
 	  redirect_to blogs_path
 end
 def show 
 	@blog = Blog.find(params[:id])
  
 end
 def edit
   @blog = Blog.find(params[:id])
 end
  def update
 	@blog = Blog.find(params[:id])
 	if @blog.update(blog_params)
 		redirect_to @blog
 	else
 		render 'edit'
 	end
 end
def create
  @blog = Blog.new(blog_params.merge(:user_id=>current_user.id))
 
  if @blog.save
    redirect_to blog_path(@blog)
  else
    render 'new'
  end
end
def notification

  @notification= Notification.where("user_id=?",current_user.id).order(created_at: :desc)
  render 'notification'
  
end
def change_val

  @notification= Notification.find(params[:id])
  if @notification.read == false
    @notification.update(:read=>true)
    redirect_to blog_path(@notification.blog_id) 
  else
    redirect_to blogs_notification_path
  end
end
def myblog
  @blogs=Blog.where("user_id=?",current_user.id)
  render 'myblog'
end

private
  def blog_params
    params.require(:blog).permit(:title, :body)
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
 
  
  <p>
    <%= form.label :Title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :Body %><br>
    <%= form.text_area :body %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 

app/views/blogs/home.html.erb
 <!-- 
<% if user_signed_in?%>
	<%= link_to 'LOGOUT',destroy_user_session_path, method: :delete%>
	<%= link_to 'Edit profile', edit_user_registration_path %> |
<%else%>
	<%= link_to 'Register here', new_user_registration_path%>
	<%= link_to 'Login here', new_user_session_path%>
<%end%> -->


<%= image_tag("blog.jpg", :alt => "rss feed",style:"width:100%") %>

app/views/blogs/index.html.erb
<table class="table table-striped" style="width:100%" align="center">
  <tr>
    <th style="font-size: 20px;">Blogger Name</th>
    <th style="font-size: 20px;">Title</th>
    <th style="font-size: 20px;">Body</th>
    <th colspan="3" style="font-size: 20px;">Action</th>
  </tr>
    <% @blog.each do |blog| %>
   
      <tr>
        <td><%= blog.user.username %></td>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog_path(blog) %></td>
      </tr>
   
<% end %>
</table>

app/views/blogs/myblog.html.erb
<table class="table table-striped" style="width:100%" align="center">
  <tr>
    <th style="font-size: 20px;">Blogger Name</th>
    <th style="font-size: 20px;">Title</th>
    <th style="font-size: 20px;">Body</th>
    <th colspan="3" style="font-size: 20px;">Action</th>
  </tr>
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.user.username %></td>
      <td><%= blog.title %></td>
      <td><%= blog.body %></td>
      <td><%= link_to 'Show', blog_path(blog) %></td>
      <td><%= link_to 'Edit',  edit_blog_path(blog) %></td>
      <td><%= link_to 'Destroy', blog_path(blog),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
     
    </tr>
  <% end %>
</table>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
 
  
  <p>
    <%= form.label :Title %><br>
    <%= form.text_field :title, class:"form-control" %>
  </p>
 
  <p>
 <div class="form-group">
  <label for="comment">Body:</label>
    <%= form.text_area :body, class:"form-control" %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 

app/views/blogs/notification.html.erb
<table class="table table-striped" style="width:100%" align="center">
<h4 style="color: blue">Your Blogs Comments</h4>
	<%puts "==========================="%>
	<%#puts @notifications.notifiable_type%>

    <% @notification.each do |notification| %>
		<tr>
  			<td>
 				 <%=  notification.notifiable.user.username %>
 				 <%= notification.notifiable_type %>
  			     <%= "your" %>
                 <%= notification.blog.title%>	
                 <% if notification.read == false%>
                 <%= link_to'<button style="background-color:lightgreen;">Unread</button>'.html_safe,change_val_path(notification)%>
                 <% else %>
                 <%= link_to'<button style="background-color:lightblue;">Read</button>'.html_safe,change_val_path(notification)%>
                 <% end %>
			</td>
  		</tr>
	<% end %>
</table>

app/views/blogs/show.html.erb
<p>
  <strong style="font-size: 20px; ">Title:</strong>
  <b style="font-size: 20px;"> <%= @blog.title  %></b>
</p>
 
<p>
  <strong style="font-size: 20px;">Text:</strong>
  <%= @blog.body%>
</p>
<p>
  <strong style="font-size: 20px;">Created At:</strong>
  <%= @blog.created_at%>
</p>
<p>
  <strong style="font-size: 20px;">Created By:</strong>
  <%= @blog.user.username%>
</p>
</br>
</br>
<p>
  <b>
  <%= @blog.likes.count%><%= ' Likes'%>
  </b>  

    <% if !like_exist%>
      <%= link_to '<span class="glyphicon glyphicon-thumbs-up"></span>'.html_safe  , blog_likes_path(@blog),method: :post %>
    <% else %>
      <%= link_to '<span class="glyphicon glyphicon-thumbs-down"></span>'.html_safe  , blog_like_path(@blog),method: :delete %>
    <% end%>
</p>

<p>
 <% @blog.comments.each do |blog| %>
    <b>Commentor:  </b><%= blog.user.username%></br>
    <b>Comment:  </b><%= blog.opinion %></td>
  </p>

<% end %>

 </div>
<a data-toggle="modal" data-target="#myModalmy">
        Comment</a>
<%= render 'comments/form' %>











<!-- 


<a href="javascript:void(0)" id="Add">Add comment</a>
   <div id="divform">
   <%= render 'comments/form' %>

   <a href="javascript:void(0)" id="close">Close</a>
 </div>
 <script type="text/javascript">
  window.onload = function(){
  var link =  document.getElementById('Add');
  var divform  =   document.getElementById('divform');
  var close = document.getElementById('close');  
  link.onclick = function(){
      divform.style.display = 'block'
    }  
    close.onclick = function(){
      divform.style.display = 'none';
     }
   }
 </script>
 -->