config/routes.rb
Rails.application.routes.draw do
  root 'blogs#home'
  get 'blogs/notification'
  post 'blogs/notification'
  post 'blogs/myblog'
  get 'change_val/:id', to: 'blogs#change_val', as: 'change_val'
  devise_for :users
  resources :blogs do
  resources :comments
  end
  resources :blogs do
  resources :likes
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :notification, as: :notifiable, dependent: :destroy
  belongs_to :user
  belongs_to :blog
end

app/models/like.rb
class Like < ApplicationRecord
  has_many :notification, as: :notifiable, dependent: :destroy
  belongs_to :user
  belongs_to :blog
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :blog
  belongs_to :notifiable , polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,authentication_keys: [:username]
 	has_many :blogs , dependent: :destroy
 	has_many :comments, dependent: :destroy


 	after_create :welcome_send
 	def welcome_send
 		WelcomeMailer.welcome_send(self).deliver
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	add_flash_types :info, :danger, :warning, :success

protected

	def configure_permitted_parameters
			added_attrs = [:username, :email, :password, :password_confirmation]
			devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
# devise_parameter_sanitizer.permit :account_update, keys: added_attrs
	end


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 before_action :authenticate_user!,except: []
def new
  @blog = Blog.new
end
 
 def index
 	@blog=Blog.all
 end
 def destroy
 	  @blog = Blog.find(params[:id])
 	  @blog.destroy
 	  redirect_to blogs_path
 end
 def show 
 	@blog = Blog.find(params[:id])
  
 end
 def edit
   @blog = Blog.find(params[:id])
 end
  def update
 	@blog = Blog.find(params[:id])
 	if @blog.update(blog_params)
 		redirect_to @blog
 	else
 		render 'edit'
 	end
 end
def create
  @blog = Blog.new(blog_params.merge(:user_id=>current_user.id))
 
  if @blog.save
    redirect_to blog_path(@blog)
  else
    render 'new'
  end
end
def notification

  @notification= Notification.where("user_id=?",current_user.id).order(created_at: :desc)
  render 'notification'
  
end
def change_val

  @notification= Notification.find(params[:id])
  if @notification.read == false
    @notification.update(:read=>true)
    redirect_to blog_path(@notification.blog_id) 
  else
    redirect_to blogs_notification_path
  end
end
def myblog
  @blogs=Blog.where("user_id=?",current_user.id)
  render 'myblog'
end

private
  def blog_params
    params.require(:blog).permit(:title, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 before_action :authenticate_user!
	def create
		@blog = Blog.find(params[:blog_id])
		@comment =@blog.comments.create(comment_params.merge(:user_id=>current_user.id))
		if @blog.user_id != current_user.id
		Notification.create(:user_id => @blog.user_id, :blog => @blog, :notifiable=> @comment, :read=>false)
	    end
	    redirect_to blog_path(@blog)
	end
	private
	def comment_params
		params.require(:comment).permit(:opinion)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	 before_action :authenticate_user!
  def new
  		 @like = Like.new
  	end

	def create
      @blog = Blog.find(params[:blog_id])
      if Like.where(user_id: current_user.id , blog_id: @blog).present? 

       # flash[:danger]= "Already  Liked"
       redirect_to blog_path(@blog)
       return false
      else
      	@like = @blog.likes.create(user_id: current_user.id)
        # render json:Notification.create(:user => current_user, :blog => @blog, :notifiable=> @like) 
        # return
        if @blog.user_id != current_user.id
        Notification.create(:user_id => @blog.user_id, :blog => @blog, :notifiable=> @like,  :read=>false)
        end
        redirect_to blog_path(@blog)
        flash[:success]= " Liked"
        return true
     end
  	end
    def destroy
      @blog = Blog.find(params[:id])
      @like=Like.where(user_id: current_user.id , blog_id: @blog).take
      @like.destroy
      redirect_to  blog_path(@blog)
    end

  	def show
  		redirect_to blog_path(@blog)
  	end
  	def index
  	end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def mycount
		Notification.where(read:false, user:current_user).count
	end
	def like_exist
       Like.where(user_id: current_user , blog_id: @blog).present?
  	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/_login_navebar.html.erb
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header" >
       <ul class="nav navbar-nav">
       <li><img src="/assets/logo1.png" style="width:140px; margin-top: 2px;"></li>
       <li><%= link_to 'Shows Blogs',blogs_path %></li>
     </ul>
    </div>
    <ul class="nav navbar-nav navbar-right">
     </li>
     <li><%= link_to "Login", new_user_session_path %></li>
     <!--  <li><span class="glyphicon glyphicon-log-in" style="color:white; width: 50px, height:50px"></span></li>  -->
      <li><%= link_to 'Sign Up',new_user_registration_path %></li>
       
    </ul>
  </div>
</nav> 

app/views/layouts/_navebar.html.erb
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header" >
       <img src="/assets/logo1.png" style="width:140px; margin-top: 2px;">
    </div>
    <ul class="nav navbar-nav">
      
      
      <li><%= link_to 'Create Blog',new_blog_path %></a></li>
      <li><%= link_to 'Shows Blogs',blogs_path %></li>
      <li><%= link_to 'your Blogs',blogs_myblog_path, method: :post %></li>
      <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
      
      
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><a data-toggle="modal" data-target="#myModal">
         <span class="glyphicon glyphicon-bell"></span>
        <span class="badge"><%= mycount%></span></li>
      <span class="glyphicon glyphicon-log-out" ></span> 
      <%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
       
    </ul>
  </div>
</nav> 

app/views/layouts/_notification.html.erb
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<div id="myModal" class="modal fade" role="dialog">
	<div class="col-md-4 col-md-offset-8">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;
					</button>
						<h4 class="modal-title">Notification</h4>
				</div>
				<% if user_signed_in?%>
				<% @notification = Notification.where("user_id =?", current_user.id)%>
					<table>
					<% @notification.each do |notification| %>
						<div style="padding-left: 13px; color: blue;">
						 <tr>
						 	<td><%= notification.notifiable.user.username %>
 					 	 		<%= notification.notifiable_type %>
  				     	 		<%= "your" %>
            	    			<%= notification.blog.title%></td>
                			 		<td><% if notification.read == false%>
                 						<%= link_to'<button style="background-color:lightgre	en;">Unread</button>'.html_safe,change_val_path(notification)%></br>
                 					<% else %>
                 						<%= link_to'<button style="background-color:lightblue;">Read</button>'.html_safe,blog_path(notification.blog)%></br>
		                 			<% end %>
		                 		</td><tr>
							</div>
						<% end %>
						</table>
				<% else %>

				<%end%>
			<div class="modal-footer">
			</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
      <% if current_user != nil %>
      <%= render 'layouts/navebar'%>
      <%= render 'layouts/notification'%>
      <% else %>
      <%= render 'layouts/login_navebar'%>
      <% end%>
     <% flash.each do |key, msg| %>
        <div class="alert alert-<%= key %>">
         <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= msg %>    
        </div>
      <% end %>
    <%= yield %>
    
  </body>
</html>